name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Site
      run: npm run build

    - name: List dist contents
      run: ls -la ./dist

    - name: Netlify Actions
      uses: nwtgck/actions-netlify@v3.0.0
      with:
        publish-dir: ./dist
        production-deploy: true
      env:
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Check Secrets Availability
      run: |
          echo "Auth token length: ${#NETLIFY_AUTH_TOKEN}"
          echo "Site ID length: ${#NETLIFY_SITE_ID}"
      env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
